"""
This type stub file was generated by pyright.
"""

from app.api.schemas import AutofillRequest, AutofillResponse, HealthResponse, ProcessPdfRequest, ProcessPdfResponse

"""API route handlers."""
router = ...
@router.get("/health", response_model=HealthResponse)
async def health_check() -> HealthResponse:
    """Health check endpoint."""
    ...

@router.post("/autofill", response_model=AutofillResponse)
async def autofill(request: AutofillRequest) -> AutofillResponse:
    """
    Process autofill request and return form field data.

    This endpoint receives information about a form and returns
    the data to fill in the form fields.
    """
    ...

@router.post("/process-pdf", response_model=ProcessPdfResponse)
async def process_pdf(request: ProcessPdfRequest) -> ProcessPdfResponse:
    """
    Process a PDF and match extracted data to form fields.

    1. Extract text from PDF using OCR
    2. Use AI to match extracted data to form fields
    3. Return mappings for user confirmation
    """
    ...

@router.get("/forms")
async def list_forms() -> dict[str, list[str]]:
    """List available form templates."""
    ...

