"""
This type stub file was generated by pyright.
"""

"""AI service for matching PDF data to form fields."""
class AIMatcherService:
    """Service for AI-powered field matching."""
    def __init__(self) -> None:
        """Initialize the AI service."""
        ...
    
    def match_fields(self, extracted_text: str, form_fields: list[dict[str, str]]) -> list[dict[str, str]]:
        """
        Use GPT to match extracted PDF text to form fields.

        Args:
            extracted_text: Text extracted from the PDF via OCR.
            form_fields: List of form field definitions from the page.

        Returns:
            List of field mappings with values.
        """
        ...
    


ai_matcher_service = ...
