"""
This type stub file was generated by pyright.
"""

from typing import Any

"""OCR service for extracting text from PDFs."""
class OCRService:
    """Service for OCR processing of PDF documents."""
    def __init__(self) -> None:
        """Initialize the OCR service."""
        ...
    
    def extract_text_from_pdf(self, pdf_base64: str) -> str:
        """
        Extract text from a PDF using OCR.

        Args:
            pdf_base64: Base64 encoded PDF data.

        Returns:
            Extracted text from the PDF.
        """
        ...
    
    def extract_structured_data(self, text: str) -> dict[str, Any]:
        """
        Try to extract structured data from text.

        This is a simple heuristic extraction. The AI matching
        will do the heavy lifting.
        """
        ...
    


ocr_service = ...
