"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Any

"""OCR service for extracting text from PDFs."""

class OCRMode(str, Enum):
    """Available OCR modes."""
    TESSERACT = "tesseract"
    DEEPDOCTECTION = "deepdoctection"


class OCRService:
    """Service for OCR processing of PDF documents."""
    def __init__(self) -> None:
        """Initialize the OCR service."""
        ...
    
    def extract_text_from_pdf(
        self, pdf_base64: str, mode: OCRMode = OCRMode.TESSERACT
    ) -> str:
        """
        Extract text from a PDF using OCR.

        Args:
            pdf_base64: Base64 encoded PDF data.
            mode: OCR mode to use (tesseract or deepdoctection).

        Returns:
            Extracted text from the PDF.
        """
        ...
    
    def is_deepdoctection_available(self) -> bool:
        """Check if deepdoctection mode is available."""
        ...
    
    def extract_structured_data(self, text: str) -> dict[str, Any]:
        """
        Try to extract structured data from text.

        This is a simple heuristic extraction. The AI matching
        will do the heavy lifting.
        """
        ...
    


ocr_service: OCRService = ...
