"""
This type stub file was generated by pyright.
"""

from contextlib import asynccontextmanager
from collections.abc import AsyncIterator
from fastapi import FastAPI

"""Main FastAPI application."""
@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    """Application lifespan events."""
    ...

def create_app() -> FastAPI:
    """Create and configure the FastAPI application."""
    ...

app = ...
if __name__ == "__main__":
    ...
